### ISSUE TITLE
Better way to use flask and other libs

### ISSUE THREAD

**Issue by andrejcermak** [OSC/ood-example-sciGatewayApp#2]
Hi, 
I just found this repo and I am curious whether it would be possible to do the installation of flask other way. There is also [this repository under OSC](https://github.com/OSC/ood-example-flask-app) that contains requirements.txt and setup file, but it does not seem to be working.

**Comment by andrejcermak** [comment]
Hi, 
I found a solution to this issue and I already created a [merge request](https://github.com/OSC/ood-example-flask-app/pull/2). Please feel free to review and consider incorporating it into this example if it's suitable.

**Comment by johrstrom** [comment]
I think you should open a ticket on that other repository - I was able to get the other repository to boot but just had to be careful about the python version I was using when issuing `setup.sh`.

**Comment by andrejcermak** [comment]
How did you boot the repo? I tried to go with My Sandbox Apps (Development) -> New app -> Clone existing app -> use the git repo of the flask example app, the result is Error starting web application

```
/var/www/ood/apps/dev/xcermak5/gateway/FlaskApp2/bin/python: line 2: /var/www/ood/apps/dev/xcermak5/gateway/FlaskApp2/.venv/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/opt/ood/ondemand/root/usr/share/passenger/helper-scripts/wsgi-loader.py", line 369, in <module>
    app_module = load_app()
  File "/opt/ood/ondemand/root/usr/share/passenger/helper-scripts/wsgi-loader.py", line 76, in load_app
    return imp.load_source('passenger_wsgi', startup_file)
  File "/var/www/ood/apps/dev/xcermak5/gateway/FlaskApp2/passenger_wsgi.py", line 1, in <module>
    from app import MyApp
  File "/home/xcermak5/ondemand/dev/FlaskApp2/app.py", line 1, in <module>
    from flask import Flask, render_template
ImportError: No module named flask
```

**Comment by johrstrom** [comment]
You need to run `setup.sh` outside of the UI.  The issue I got into was _where_ I ran `setup.sh` and if that python version matched up with what's on the OOD webserver.

That is - you run `setup.sh` on say a login node for example.  When the app boots - it boots on the OOD's webserver, with the OOD webserver's python. So they have to match, the python environment of the OOD webserver and the python environment of wherever you issued `setup.sh`.

**Comment by andrejcermak** [comment]
Ah I see. Do you think it is possible to automate the execution of the `setup.sh` in order to simplify the app initialization from git in OOD?

**Comment by johrstrom** [comment]
> Do you think it is possible to automate the execution of the setup.sh in order to simplify the app initialization from git in OOD?

Yes! Though there could be buttons for the same.  If you'd like to open a ticket on https://github.com/OSC/ondemand, that'd be just fine!

ruby apps have this button for the same thing (installing dependencies through bundler). My guess is that we support that because we're ruby developers. 
![image](https://github.com/OSC/ood-example-sciGatewayApp/assets/4874123/14525ae6-fe2d-47b0-be71-6e9dedd87d4c)

But with python having a plethora of `virtualenv`, `conda` and maybe others we'd probably have to set a button for each and I'm not sure if we can (or should) to it _automatically_ given the different variations.

**Comment by andrejcermak** [comment]
Thank you for the insights @johrstrom!
